### ISSUE TITLE
Implementation of reverse deformation and PE in PPDM 

### ISSUE THREAD

**Issue by severous** [FlappyPeggy/DMAD#2]
Thanks for your excellent work.
I have some questions about the implementation of PPDM 
-  I would like to know the implementation details of the $PE(\cdot)$ operation in Equation $\psi^{\prime}(x)=Up(h^{\prime}(P E(x)))$. Besides, I would like to know the difference between PE and CoordConv. Can you provide some code references？
-  $L_{c y c}=\left\|x-x \circ O_1 \cdots \circ O_K \circ O_K^T \cdots \circ O_1^T\right\|_2$. Could you provide some implementation details of the grid-sampling function $\circ$?

Thanks for your reply:)

**Comment by FlappyPeggy** [comment]
- $PE(\cdot)$ is the AddCoords2d function in CoorConv2d, where CoorConv2d apply a Conv2d after $PE(\cdot)$. You can find the code in resnet.py -> class OffsetNet -> self.conv_offset1 and the definition is at the beginning of the code.
- The function $\circ$ is just a torch function: F.grid_sample. 
- I apologize for removing the PPDM version "test.py" (including the references of $\circ$) at the moment, as I noticed that someone misunderstood our code. If you need to test PPDM, you can refer to the PDM version or provide an email address so that I can send you the uncleaned (but runnable) code.

**Comment by FlappyPeggy** [comment]
>     * I apologize for removing the PPDM version "test.py" (including the references of ∘) at the moment, as I noticed that someone misunderstood our code. If you need to test PPDM, you can refer to the PDM version or provide an email address so that I can send you the uncleaned (but runnable) code.

an untested version has been uploaded :)

**Comment by severous** [comment]
Thanks for your reply. My email address is Chromosomer@outlook.com. please send me the code about PDM and PPDM.

**Comment by FlappyPeggy** [comment]
> Thanks for your reply. My email address is [Chromosomer@outlook.com](mailto:Chromosomer@outlook.com). please send me the code about PDM and PPDM.

I have re-uploaded this version :)

**Comment by FlappyPeggy** [comment]
re-uploaded the file
