### ISSUE TITLE
About the scope of the deformation

### ISSUE THREAD

**Issue by ck-w-0** [FlappyPeggy/DMAD#9]
hi, for the control of deformation, how to control its deformation in a controllable range, so as not to become abnormal. See if the code uses the max_offset parameter?

**Comment by FlappyPeggy** [comment]
Due to the previous $TanH: x \rightarrow [-1, 1]$, the max_offset controls the deformation amplitude $TanH: x \rightarrow [-2maxoffset/l, 2maxoffset/l]$ for each layer. Smoothness and amplitude constraints are imposed on the output of this term. The sum of max_offset should be larger than the maximum deformation of normals for given memory quantity. When this value is further increased, $L_{df}$ could produces stronger regularization effect for compensation.

This suppresses shortcut learning that may destroy "positive correlation" within representation capacity.

**Comment by ck-w-0** [comment]
> Due to the previous TanH:x→[−1,1], the max_offset controls the deformation amplitude TanH:x→[−2maxoffset/l,2maxoffset/l] for each layer. Smoothness and amplitude constraints are imposed on the output of this term. The sum of max_offset should be larger than the maximum deformation of normals for given memory quantity. When this value is further increased, Ldf could produces stronger regularization effect for compensation.
> 
> This suppresses shortcut learning that may destroy "positive correlation" within representation capacity.
Thank you for your patience!
If I could by max_offsets the parameters, to produce "abnormal"?

**Comment by FlappyPeggy** [comment]
If you want to produce "abnormal", max_offsets should be enlarged.

**Comment by ck-w-0** [comment]
> If you want to produce "abnormal", max_offsets should be enlarged

thx，great work, very inspiring.
